export const algId = {
    "3x3": {
        "oll": {
            "1": ['OLL 1 (L-Shape)', 'oll1', "R U2' R2' F R F' U2' R' F R F'"],
            "2": ['OLL 2 (L-Shape)', 'oll2', "L F L' U2 R U2' R' U2 L F' L'"],
            "3": ['OLL 3 (P-Shape)', 'oll3', "r' R2 U R' U r U2' r' U M'"],
            "4": ['OLL 4 (P-Shape)', 'oll4', "l L2' U' L U' l' U2 l U' M'"],
            "5": ['OLL 5 (L-Shape)', 'oll5', "l' U2 L U L' U l"],
            "6": ['OLL 6 (L-Shape)', 'oll6', "r U2' R' U' R U' r'"],
            "7": ['OLL 7 (Corner OLL)', 'oll7', "r U R' U R U2' r'"],
            "8": ['OLL 8 (Corner OLL)', 'oll8', "l' U' L U' L' U2 l"],
            "9": ['OLL 9 (F-Shape)', 'oll9', "R U R' U' R' F R2 U R' U' F'"],
            "10": ['OLL 10 (F-Shape)', 'oll10', "r R2' U2 R U R' U R U R r'"],
            "11": ['OLL 11 (Square)', 'oll11', "S' U2 R U R' U R U2' R' S"],
            "12": ['OLL 12 (Cross OLL)', 'oll12', "M' R' U' R U' R' U2 R U' R r'"],
            "13": ['OLL 13 (T-Shape)', 'oll13', "F U R U' R2' F' R U R U' R'"],
            "14": ['OLL 14 (T-Shape)', 'oll14', "R' F R U R' F' R F U' F'"],
            "15": ['OLL 15 (Fish Shape)', 'oll15', "l' U' l L' U' L U l' U l"],
            "16": ['OLL 16 (Fish Shape)', 'oll16', "r U r' R U R' U' r U' r'"],
            "17": ['OLL 17 (Diagonal Cross)', 'oll17', "F R' F' R2 r' U R U' R' U' M'"],
            "18": ['OLL 18 (Diagonal Cross)', 'oll18', "r U R' U R U2' r2 U' R U' R' U2' r"],
            "19": ['OLL 19 (Diagonal Cross)', 'oll19', "r' R U R U R' U' M' R' F R F'"],
            "20": ['OLL 20 (Diagonal Cross)', 'oll20', "r U R' U' M2 U R U' R' U' M'"],
            "21": ['OLL 21 (Solved OLL / Full Cross)', 'oll21', "R U R' U R U' R' U R U2' R'"], 
            "22": ['OLL 22 (L-Shape)', 'oll22', "R U2' R2' U' R2 U' R2' U2' R"],
            "23": ['OLL 23 (Cross OLL)', 'oll23', "R2 D R' U2 R D' R' U2 R'"],
            "24": ['OLL 24 (Cross OLL)', 'oll24', "r U R' U' r' F R F'"],
            "25": ['OLL 25 (Cross OLL)', 'oll25', "F R' F' r U R U' r'"],
            "26": ['OLL 26 (Sune)', 'oll26', "R U2' R' U' R U' R'"], 
            "27": ['OLL 27 (Anti-Sune)', 'oll27', "R U R' U R U2 R'"],
            "28": ['OLL 28 (Headlights)', 'oll28', "r U R' U' r' R U R U' R'"],
            "29": ['OLL 29 (Chameleon)', 'oll29', "l D l' U l D' l2' U l U' l' U' l"],
            "30": ['OLL 30 (Chameleon)', 'oll30', "r' D' r U' r' D r2 U' r' U r U r'"],
            "31": ['OLL 31 (L-Shape)', 'oll31', "R' U' F U R U' R' F' R"],
            "32": ['OLL 32 (L-Shape)', 'oll32', "L U F' U' L' U L F L'"],
            "33": ['OLL 33 (T-Shape)', 'oll33', "R U R' U' R' F R F'"],
            "34": ['OLL 34 (T-Shape)', 'oll34', "f R f' U' r' U' R U M'"],
            "35": ['OLL 35 (Cross OLL)', 'oll35', "R U2' R2' F R F' R U2' R'"],
            "36": ['OLL 36 (Cross OLL)', 'oll36', "L' U' L U' L' U L U L F' L' F"],
            "37": ['OLL 37 (Arrowhead)', 'oll37', "F R' F' R U R U' R'"],
            "38": ['OLL 38 (Arrowhead)', 'oll38', "R U R' U R U' R' U' R' F R F'"],
            "39": ['OLL 39 (W-Shape)', 'oll39', "f' L F L' U' L' U L S"],
            "40": ['OLL 40 (W-Shape)', 'oll40', "f R' F' R U R U' R' S'"],
            "41": ['OLL 41 (Awkward T)', 'oll41', "R U R' U R U2 R' F R U R' U' F'"],
            "42": ['OLL 42 (Awkward T)', 'oll42', "R' F R F' R' F R F' R U R' U' R U R'"],
            "43": ['OLL 43 (Small L)', 'oll43', "R' U' F' U F R"],
            "44": ['OLL 44 (Small L)', 'oll44', "F U R U' R' F'"],
            "45": ['OLL 45 (Small Lightning)', 'oll45', "F R U R' U' F'"],
            "46": ['OLL 46 (Small Lightning)', 'oll46', "R' U' R' F R F' U R"],
            "47": ['OLL 47 (Dot OLL)', 'oll47', "F R' F' R U2 R U' R' U R U2 R'"],
            "48": ['OLL 48 (Dot OLL)', 'oll48', "F R U R' U' R U R' U' F'"],
            "49": ['OLL 49 (Half Cross - Bar on Side)', 'oll49', "r U' r2' U r2 U r2' U' r"],
            "50": ['OLL 50 (Half Cross - Bar on Side)', 'oll50', "l' U l2 U' l2' U' l2 U l'"],
            "51": ['OLL 51 (Half Cross - Checkers)', 'oll51', "F U R U' R' U R U' R' F'"],
            "52": ['OLL 52 (Half Cross - Checkers)', 'oll52', "R' F' U' F U' R U R' U R"],
            "53": ['OLL 53 (Adjacent Corners Oriented)', 'oll53', "l' U' L U' L' U L U' L' U2 l"],
            "54": ['OLL 54 (Adjacent Corners Oriented)', 'oll54', "r U R' U R U' R' U R U2 r'"],
            "55": ['OLL 55 (Fish Shape)', 'oll55', "R' F U R U' R2' F' R2 U R' U' R"],
            "56": ['OLL 56 (Fish Shape)', 'oll56', "r U r' U R U' R' U R U' M' U' r'"],
            "57": ['OLL 57 (Dot OLL - Solved Case)', 'oll57', "R U R' U' M' U R U' r'"] 
        },
        "pll": {
            "1": ['A-Perm (Aa)', 'pll_aa', "x L2 D2 (L' U' L) D2 (L' U L')"],
            "2": ['A-Perm (Ab)', 'pll_ab', "x' L2 D2 (L U L') D2 L U' L"],
            "3": ['E-Perm', 'pll_e', "x' (L' U L D') (L' U' L D) (L' U' L D') (L' U L D)"],
            "4": ['H-Perm', 'pll_h', "M2 U M2 U2 M2 U M2"],
            "5": ['Z-Perm', 'pll_z', "M' U (M2 U M2 U) M' U2 M2"],
            "6": ['U-Perm (Ua)', 'pll_ua', "M2 U (M U2 M') U M2"],
            "7": ['U-Perm (Ub)', 'pll_ub', "M2 U' (M U2 M') U' M2"],
            "8": ['F-Perm', 'pll_f', "(R' U' F') R U R' U' R' F R2 U' R' U' R U R' U R"],
            "9": ['J-Perm (Ja)', 'pll_ja', "x R2 F R F' R U2 r' U r U2"],
            "10": ['J-Perm (Jb)', 'pll_jb', "(R U R' F') (R U R' U') R' F R2 U' R'"],
            "11": ['R-Perm (Ra)', 'pll_ra', "(R U' R' U') (R U R D) (R' U' R D') R' U2 R'"],
            "12": ['R-Perm (Rb)', 'pll_rb', "R2 F R (U R U' R') F' R U2 R' U2 R"],
            "13": ['T-Perm', 'pll_t', "(R U R' U') R' F R2 (U' R' U') (R U R' F')"],
            "14": ['Y-Perm', 'pll_y', "F (R U' R' U') (R U R' F') (R U R' U') (R' F R F')"],
            "15": ['V-Perm', 'pll_v', "R' U R' U' y R' F' R2 U' R' U R' F R F"],
            "16": ['N-Perm (Na)', 'pll_na', "R U R' U (R U R' F' R U R' U' R' F R2 U' R') U2 R U' R'"],
            "17": ['N-Perm (Nb)', 'pll_nb', "R' (U R U' R') (F' U' F) (R U R' F) R' F' R U' R"],
            "18": ['G-Perm (Ga)', 'pll_ga', "R2 U R' U R' U' R U' R2 (U' D) R' U R D'"],
            "19": ['G-Perm (Gb)', 'pll_gb', "R' U' R (U D') R2 U R' U R U' R U' R2 D"],
            "20": ['G-Perm (Gc)', 'pll_gc', "R2 U' R U' R U R' U R2 (U D') R U' R' D"],
            "21": ['G-Perm (Gd)', 'pll_gd', "R U R' (U' D) R2 U' R U' R' U R' U R2 D'"]
        }
    },
    "4x4": {
        "1": ['PLL Parity', 'pllpar', "Rw2 U2 Rw2 Uu2 Rw2 Uu2"],
        "2": ['OLL Parity', 'ollpar', "Rw U2 x Rw U2 Rw U2' Rw' U2 Lw U2 Rw' U2 Rw U2' Rw' U2'"],
    },
    "5x5": {
        "1": ['L2E Case 1', 'l2e1', " "], 
        "2": ['L2E Case 2', 'l2e2', " "],
        "3": ['L2E Case 3', 'l2e3', " "],
        "4": ['L2E Case 4', 'l2e4', " "],
        "5": ['L2E Case 5', 'l2e5', " "],
        "6": ['L2E Case 6', 'l2e6', " "],
        "7": ['L2E Case 7', 'l2e7', " "],
        "8": ['L2E Case 8', 'l2e8', " "],
        "9": ['L2E Case 9', 'l2e9', " "],
        "10": ['L2E Case 10', 'l2e10', " "],
        "11": ['L2E Case 11', 'l2e11', " "],
        "12": ['L2E Case 12', 'l2e12', " "] 
    }
};